// <auto-generated />
using System;
using GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameData.Migrations
{
    [DbContext(typeof(GameDataContext))]
    [Migration("20210507073347_attempt1")]
    partial class attempt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameData.Ammo", b =>
                {
                    b.Property<string>("AmmoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DamageID")
                        .HasColumnType("int");

                    b.Property<int?>("GunID")
                        .HasColumnType("int");

                    b.HasKey("AmmoID");

                    b.HasIndex("DamageID");

                    b.HasIndex("GunID");

                    b.ToTable("Ammos");
                });

            modelBuilder.Entity("GameData.Damage", b =>
                {
                    b.Property<int>("DamageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Blunt")
                        .HasColumnType("int");

                    b.Property<int?>("ElementalDamageElementalID")
                        .HasColumnType("int");

                    b.Property<int>("Pierce")
                        .HasColumnType("int");

                    b.Property<int>("Strike")
                        .HasColumnType("int");

                    b.HasKey("DamageID");

                    b.HasIndex("ElementalDamageElementalID");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("GameData.Elemental", b =>
                {
                    b.Property<int>("ElementalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Electricity")
                        .HasColumnType("int");

                    b.Property<int>("Fire")
                        .HasColumnType("int");

                    b.Property<int>("Ice")
                        .HasColumnType("int");

                    b.Property<int>("Poison")
                        .HasColumnType("int");

                    b.HasKey("ElementalID");

                    b.ToTable("Elementals");
                });

            modelBuilder.Entity("GameData.Gun", b =>
                {
                    b.Property<int>("GunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FireRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartyMemberID")
                        .HasColumnType("int");

                    b.HasKey("GunID");

                    b.HasIndex("PartyMemberID");

                    b.ToTable("Guns");
                });

            modelBuilder.Entity("GameData.PartyMember", b =>
                {
                    b.Property<int>("PartyMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("PartyMemberID");

                    b.ToTable("PartyMember");
                });

            modelBuilder.Entity("GameData.Ammo", b =>
                {
                    b.HasOne("GameData.Damage", "Damage")
                        .WithMany()
                        .HasForeignKey("DamageID");

                    b.HasOne("GameData.Gun", null)
                        .WithMany("Ammos")
                        .HasForeignKey("GunID");

                    b.Navigation("Damage");
                });

            modelBuilder.Entity("GameData.Damage", b =>
                {
                    b.HasOne("GameData.Elemental", "ElementalDamage")
                        .WithMany()
                        .HasForeignKey("ElementalDamageElementalID");

                    b.Navigation("ElementalDamage");
                });

            modelBuilder.Entity("GameData.Gun", b =>
                {
                    b.HasOne("GameData.PartyMember", null)
                        .WithMany("Guns")
                        .HasForeignKey("PartyMemberID");
                });

            modelBuilder.Entity("GameData.Gun", b =>
                {
                    b.Navigation("Ammos");
                });

            modelBuilder.Entity("GameData.PartyMember", b =>
                {
                    b.Navigation("Guns");
                });
#pragma warning restore 612, 618
        }
    }
}
